version: "3.10"

services:
  web_space_station:
    container_name: web_space_station
    build:
      context: ./
    volumes:
      - ./app/:/src
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    command: >
      sh -c "python ./src/manage.py makemigrations && 
             python ./src/manage.py migrate &&
             python ./src/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db_space

  db_space:
    image: postgres:14.5-alpine
    container_name: db_space
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=officeuser
      - POSTGRES_PASSWORD=officeuser123
      - POSTGRES_DB=space_station
    ports:
      - "54321:5432"

volumes:
  postgres_data: