# Generated by Django 4.1.3 on 2022-12-05 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('condition', models.CharField(default='running', max_length=8)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('position_z', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_broken', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pointing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(choices=[('x', 'Axis X'), ('y', 'Axis Y'), ('z', 'Axis Z')], max_length=2)),
                ('distance', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointing_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
