# Generated by Django 4.1.3 on 2022-12-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_alter_spacestation_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacestation',
            name='position_x',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='spacestation',
            name='position_y',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='spacestation',
            name='position_z',
            field=models.IntegerField(default=100),
        ),
    ]
