openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/v1/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/v1/stations/:
    get:
      operationId: stations_list
      tags:
      - stations
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpaceStation'
          description: ''
    post:
      operationId: stations_create
      tags:
      - stations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpaceStation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SpaceStation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SpaceStation'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpaceStation'
          description: ''
  /api/v1/stations/{id}/:
    get:
      operationId: stations_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - stations
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpaceStation'
          description: ''
    put:
      operationId: stations_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - stations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpaceStation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SpaceStation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SpaceStation'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpaceStation'
          description: ''
    patch:
      operationId: stations_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - stations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSpaceStation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSpaceStation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSpaceStation'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpaceStation'
          description: ''
    delete:
      operationId: stations_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - stations
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/stations/{id}/state/:
    get:
      operationId: stations_state_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - stations
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpaceStationState'
          description: ''
    post:
      operationId: stations_state_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - stations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pointing'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pointing'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Pointing'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pointing'
          description: ''
components:
  schemas:
    AxisEnum:
      enum:
      - x
      - y
      - z
      type: string
    ConditionEnum:
      enum:
      - running
      - broken
      type: string
    PatchedSpaceStation:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
        position_x:
          type: integer
          readOnly: true
        position_y:
          type: integer
          readOnly: true
        position_z:
          type: integer
          readOnly: true
        condition:
          allOf:
          - $ref: '#/components/schemas/ConditionEnum'
          readOnly: true
        date_creation:
          type: string
          format: date-time
          readOnly: true
        date_broken:
          type: string
          format: date-time
          readOnly: true
          nullable: true
    Pointing:
      type: object
      properties:
        axis:
          $ref: '#/components/schemas/AxisEnum'
        distance:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        user:
          type: integer
          readOnly: true
      required:
      - axis
      - distance
      - user
    SpaceStation:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
        position_x:
          type: integer
          readOnly: true
        position_y:
          type: integer
          readOnly: true
        position_z:
          type: integer
          readOnly: true
        condition:
          allOf:
          - $ref: '#/components/schemas/ConditionEnum'
          readOnly: true
        date_creation:
          type: string
          format: date-time
          readOnly: true
        date_broken:
          type: string
          format: date-time
          readOnly: true
          nullable: true
      required:
      - condition
      - date_broken
      - date_creation
      - id
      - name
      - position_x
      - position_y
      - position_z
    SpaceStationState:
      type: object
      properties:
        position_x:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        position_y:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        position_z:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
      required:
      - position_x
      - position_y
      - position_z
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
